---
title: "data_clean_v1_Xuhao"
author: "Xuhao Dai"
date: "4/15/2020"
output: html_document
---
Reading data and compiling over 22M rows of raw data. Randomly select 5% of it for further analysis and modeling.
```{r}
library(tidyverse)

#birth year column might not be useful and can have outliers 
#keep single focus of analysis - effect of weather on the system 
#capacity data - just focus on demand prediction for each station 
#don't use JC data 
#do one year 1-12 then extract a sample like 5% of total data for preliminary work 

#Import all data of all months in 2019 
jan_bike <- read.csv("201901-citibike-tripdata.csv")
feb_bike <- read.csv("201902-citibike-tripdata.csv")
mar_bike <- read.csv("201903-citibike-tripdata.csv")
apr_bike <- read.csv("201904-citibike-tripdata.csv")
may_bike <- read.csv("201905-citibike-tripdata.csv")
jun_bike <- read.csv("201906-citibike-tripdata.csv")
jul_bike <- read.csv("201907-citibike-tripdata.csv")
aug_bike <- read.csv("201908-citibike-tripdata.csv")
sep_bike <- read.csv("201909-citibike-tripdata.csv")
oco_bike <- read.csv("201910-citibike-tripdata.csv")
nov_bike <- read.csv("201911-citibike-tripdata.csv")
dec_bike <- read.csv("201912-citibike-tripdata.csv")

#combine data and get train&test data
bike_total_2019<- rbind(jan_bike,feb_bike,mar_bike,apr_bike,may_bike,jun_bike,jul_bike,aug_bike,sep_bike,oco_bike,nov_bike,dec_bike)
set.seed(12345)
bike_index <- sample(1:nrow(bike_total_2019),nrow(bike_total_2019))

#extract 5% of total dataset for modeling so that data size is not too big
bike_part_5perc <- bike_total_2019[bike_index[1:(0.05*nrow(bike_total_2019))],]
bike_train <- bike_part_5perc[1:(0.8*nrow(bike_part_5perc)),]
bike_test <- bike_part_5perc[(0.8*nrow(bike_part_5perc)):nrow(bike_part_5perc),]

##Extract year, month, day, hour and min to be used for relational keys to match with weather data
bike_train$start_year <- as.factor(substr(bike_train$starttime,1,4))
bike_train$start_mth <- as.factor(substr(bike_train$starttime,6,7))
bike_train$start_day <- as.factor(substr(bike_train$starttime,9,10))
bike_train$start_hr <- as.factor(substr(bike_train$starttime,12,13))
bike_train$start_min <- as.factor(substr(bike_train$starttime,15,16))

bike_test$start_year <- as.factor(substr(bike_test$starttime,1,4))
bike_test$start_mth <- as.factor(substr(bike_test$starttime,6,7))
bike_test$start_day <- as.factor(substr(bike_test$starttime,9,10))
bike_test$start_hr <- as.factor(substr(bike_test$starttime,12,13))
bike_test$start_min <- as.factor(substr(bike_test$starttime,15,16))

##Extract year, month, date for end day
bike_train$stop_year <- as.factor(substr(bike_train$stoptime,1,4))
bike_train$stop_mth <- as.factor(substr(bike_train$stoptime,6,7))
bike_train$stop_day <- as.factor(substr(bike_train$stoptime,9,10))
bike_train$stop_hr <- as.factor(substr(bike_train$stoptime,12,13))
bike_train$stop_min <- as.factor(substr(bike_train$stoptime,15,16))

bike_test$stop_year <- as.factor(substr(bike_test$stoptime,1,4))
bike_test$stop_mth <- as.factor(substr(bike_test$stoptime,6,7))
bike_test$stop_day <- as.factor(substr(bike_test$stoptime,9,10))
bike_test$stop_hr <- as.factor(substr(bike_test$stoptime,12,13))
bike_test$stop_min <- as.factor(substr(bike_test$stoptime,15,16))

#convert birth year before 1920 to median of the data set since we assume no one who is over 100 years old would ride the bike. the data point might be mis-entry 
train_index_1920 <- bike_train$birth.year <= 1920
bike_train_birth <- bike_train
bike_train_birth$birth.year[train_index_1920] <- median(bike_train_birth$birth.year)

test_index_1920 <- bike_test$birth.year <= 1920
bike_test_birth <- bike_test
bike_test_birth$birth.year[test_index_1920] <- median(bike_test_birth$birth.year)

#Check weather data
nycw <- read.csv("nycweather.csv")

nycw$start_year <- as.numeric(substr(nycw$Date,1,4))
nycw_2019 <- subset(nycw,start_year == 2019)

nycw_2019$start_year <- as.factor(nycw_2019$start_year)
nycw_2019$start_mth <- as.factor(substr(nycw_2019$Date,6,7))
nycw_2019$start_day <- as.factor(substr(nycw_2019$Date,9,10))

#remove duplicates
library(tidyverse)
nycw_2019 <-distinct(nycw_2019)
nycw_2019 <- nycw_2019[-181,] #found two rows for 6/30/2019
str(nycw_2019)

#merge bike data with weather data 
bike_weather_train <- merge(bike_train,nycw_2019,by.x = c("start_year","start_mth","start_day"), by.y = c("start_year","start_mth", "start_day"))
str(bike_weather_train)

bike_weather_test <- merge(bike_test,nycw_2019,by.x = c("start_year","start_mth","start_day"), by.y = c("start_year","start_mth", "start_day"))
str(bike_weather_test)

#clean up the data 
bike_weather_train$bikeid <- as.factor(bike_weather_train$bikeid)
bike_weather_test$bikeid <- as.factor(bike_weather_test$bikeid)

#write train and test data to CSV file 
write.csv(bike_weather_train,"D:\\School\\Master Program - IOE\\Winter 2020\\Team project\\bike_weather_train_5perc_new.csv")
write.csv(bike_weather_test,"D:\\School\\Master Program - IOE\\Winter 2020\\Team project\\bike_weather_test_5perc.csv")


```



Further clean up to prepare train and test data for the team. 
```{r}
#convert birth year before 1920 to median of overall birth years. We assumed that people over 100 years would not likely to ride bikes and those data points are outliers. 
traindata <- read.csv("bike_weather_train_5perc.csv")

train_index_1920 <- traindata$birth.year <= 1920
bike_train_birth <- traindata
bike_train_birth$birth.year[train_index_1920] <- median(bike_train_birth$birth.year)

testdata <- read.csv("bike_weather_test_5perc.csv")

test_index_1920 <- testdata$birth.year <= 1920
bike_test_birth <- testdata
bike_test_birth$birth.year[test_index_1920] <- median(bike_test_birth$birth.year)

#eliminate rows with NAs for start.stationID and stop.stationID
bike_train_b_s <- bike_train_birth[!is.na(bike_train_birth$start.station.id),]
bike_train_b_ss <- bike_train_b_s[!is.na(bike_train_b_s$end.station.id),]

bike_test_b_s <- bike_test_birth[!is.na(bike_test_birth$start.station.id),]
bike_test_b_ss <- bike_test_b_s[!is.na(bike_test_b_s$end.station.id),]

#eliminate rows with extreme long trip duration such as 3M seconds. We assumed that those are outliers. 
outlier_tripduration_tr <- quantile(bike_train_b_ss$tripduration, 0.999)
outlier_tripduration_ts <- quantile(bike_test_b_ss$tripduration, 0.999)
outlier_tripduration_tr

bike_train_b_ss_d <- bike_train_b_ss[which(bike_train_b_ss$tripduration <= outlier_tripduration_tr),]
bike_test_b_ss_d <- bike_test_b_ss[which(bike_test_b_ss$tripduration <= outlier_tripduration_ts),]

str(bike_train_b_ss_d)

#eliminate rows with end date in 2020 to be more consistent with weather data the team is using 
bike_train_b_ss_d <- subset(bike_train_b_ss_d, stop_year <= 2019)
bike_test_b_ss_d <- subset(bike_test_b_ss_d, stop_year <= 2019)

bike_train_b_ss_d$stop_year <- as.factor(bike_train_b_ss_d$stop_year)
bike_test_b_ss_d$stop_year <- as.factor(bike_test_b_ss_d$stop_year)

#convert data types from int to factors for columns such as year, month, etc.
bike_train_b_ss_d$start_year <- as.factor(bike_train_b_ss_d$start_year)
bike_train_b_ss_d$start_mth <- as.factor(bike_train_b_ss_d$start_mth)
bike_train_b_ss_d$start_day <- as.factor(bike_train_b_ss_d$start_day)
bike_train_b_ss_d$start_hr <- as.factor(bike_train_b_ss_d$start_hr)
bike_train_b_ss_d$start_min <- as.factor(bike_train_b_ss_d$start_min)

bike_train_b_ss_d$stop_year <- as.factor(bike_train_b_ss_d$stop_year)
bike_train_b_ss_d$stop_mth <- as.factor(bike_train_b_ss_d$stop_mth)
bike_train_b_ss_d$stop_day <- as.factor(bike_train_b_ss_d$stop_day)
bike_train_b_ss_d$stop_hr <- as.factor(bike_train_b_ss_d$stop_hr)
bike_train_b_ss_d$stop_min <- as.factor(bike_train_b_ss_d$stop_min)

bike_test_b_ss_d$start_year <- as.factor(bike_test_b_ss_d$start_year)
bike_test_b_ss_d$start_mth <- as.factor(bike_test_b_ss_d$start_mth)
bike_test_b_ss_d$start_day <- as.factor(bike_test_b_ss_d$start_day)
bike_test_b_ss_d$start_hr <- as.factor(bike_test_b_ss_d$start_hr)
bike_test_b_ss_d$start_min <- as.factor(bike_test_b_ss_d$start_min)

bike_test_b_ss_d$stop_year <- as.factor(bike_test_b_ss_d$stop_year)
bike_test_b_ss_d$stop_mth <- as.factor(bike_test_b_ss_d$stop_mth)
bike_test_b_ss_d$stop_day <- as.factor(bike_test_b_ss_d$stop_day)
bike_test_b_ss_d$stop_hr <- as.factor(bike_test_b_ss_d$stop_hr)
bike_test_b_ss_d$stop_min <- as.factor(bike_test_b_ss_d$stop_min)

str(bike_train_b_ss_d)
str(bike_test_b_ss_d)

#write into csv file
write.csv(bike_train_b_ss_d,"D:\\School\\Master Program - IOE\\Winter 2020\\Team project\\bike_weather_train_clean.csv")
write.csv(bike_test_b_ss_d,"D:\\School\\Master Program - IOE\\Winter 2020\\Team project\\bike_weather_test_clean.csv")

#read the new data set and check if everything looks fine to further analysis
train_clean <- read.csv("bike_weather_train_clean.csv")
str(train_clean)
summary(train_clean)

```

