---
title: "Trip_duration_modeel_Priti"
author: "Priti"
date: "4/18/2020"
output:
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    number_sections: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Load Datasets
```{r}
#load train dataset
traindata = read.csv("train_final.csv")

#load test dataset
testdata = read.csv("test_final.csv")

str(traindata)

```

# Clean up Datasets
Ensure that no additional clean up is needed after train and test datasets are extracted from the entire 2019 usage.
```{r}

#train dataset
traindata$X.2 = NULL
traindata$X.1 = NULL
traindata$X = NULL
traindata$start_year = NULL
traindata$starttime = NULL
traindata$stop_year = NULL
traindata$stoptime = NULL
traindata$Date = NULL
traindata$start.station.name = NULL
traindata$end.station.name = NULL
traindata$usertype = NULL
traindata$day = NULL
traindata$end.station.name = NULL
traindata$end.station.name = NULL
traindata$start.station.id = as.integer(traindata$start.station.id)
traindata$end.station.id = as.integer(traindata$end.station.id)
colnames(traindata)
str(traindata)
summary(traindata)


#test dataset
testdata$X.2 = NULL
testdata$X.1 = NULL
testdata$X = NULL
testdata$start_year = NULL
testdata$starttime = NULL
testdata$stop_year = NULL
testdata$stoptime = NULL
testdata$stoptime = NULL
testdata$Date = NULL
testdata$start.station.name = NULL
testdata$end.station.name = NULL
testdata$usertype = NULL
testdata$day = NULL
testdata$start.station.id = as.integer(testdata$start.station.id)
testdata$end.station.id = as.integer(testdata$end.station.id)
colnames(testdata)
str(testdata)
summary(testdata)


library(class)

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

traindata_n <- as.data.frame(lapply(traindata[19:22], normalize))
testdata_n <- as.data.frame(lapply(testdata[19:22], normalize))
summary(traindata_n)
                
                
```

# Modeling

## Trip duration: Linear model


```{r}
#Linear model

trip_lm <- lm(tripduration ~ TMIN...C. + TMAX...C.+Ave.Wind.Speed+PRCP..mm. + SNOW..mm., data = traindata)
summary(trip_lm)

#Test model

tripPred <- predict(trip_lm, testdata) 

actuals_preds <- data.frame(cbind(actuals=testdata$tripduration, predicteds=tripPred))  # make actuals_predicteds dataframe

mape <- mean(abs((actuals_preds$predicteds - actuals_preds$actuals))/actuals_preds$actuals)  
# mean absolute percentage deviation

mape

plot(actuals_preds$actuals,actuals_preds$predicteds, main = "Actuals vs Predicted",
     xlab = "Actuals" , ylab = "Predicted")
abline(a = 0, b = 1, col = "red")



```

## Trip duration: KNN

```{r}
#KNN

train_labels <- traindata[,3]
trip_knn <- knn(train = traindata, cl = train_labels, test = testdata, k=3)

test_labels <- testdata[,3]

library(gmodels)
CrossTable(x = test_labels, y = trip_knn, 
           prop.chisq=FALSE)
#Test model

```

## Trip duration: SVM


```{r}
#SVM


library(kernlab)
trip_svm<- ksvm(tripduration ~ TMIN...C. + TMAX...C.+Ave.Wind.Speed+PRCP..mm. + SNOW..mm., data = traindata,
                          kernel = "vanilladot")

trip_svm

#Test model
trip_svm_Pred<- predict(trip_svm, testdata)
head(trip_svm_Pred)
table(trip_svm_Pred, testdata$tripduration)
svm_correct <- trip_svm_Pred == testdata$tripduration
table(svm_correct)
prop.table(table(svm_correct))

confusionMatrix(as.factor(trip_svm_Pred), as.factor(testdata$tripduration))




```

## Trip duration: Decision tree


```{r}
#Decision tree


library(C50)
trip_decision<- C5.0(testdata[-c(10 ,15)], testdata$tripduration)
trip_decision
summary(trip_decision)
#plot(trip_decision)

#Test model
trip_pred_decision <- predict(trip_decision, testdata)
library(gmodels)
CrossTable(testdata$tripduration,trip_pred_decision,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('actual trip duration', 'predicted trip duration'))


```

## Trip duration: Random forest


```{r}
#Random forest

library(randomForest)
set.seed(300)
trip_rf <- randomForest(tripduration ~ TMIN...C. + TMAX...C.+Ave.Wind.Speed+PRCP..mm. + SNOW..mm., data = traindata)
trip_rf

library(caret)
ctrl <- trainControl(method = "repeatedcv",
                     number = 10, repeats = 10)

# auto-tune a random forest
grid_rf <- expand.grid(.mtry = c(2, 4, 8, 16))

set.seed(300)
trip_m_rf <- train(tripduration ~ TMIN...C. + TMAX...C.+Ave.Wind.Speed+PRCP..mm. + SNOW..mm., data = traindata, method = "rf",
              metric = "Kappa", trControl = ctrl,
              tuneGrid = grid_rf)
trip_m_rf

# auto-tune a boosted C5.0 decision tree
grid_c50 <- expand.grid(.model = "tree",
                        .trials = c(10, 20, 30, 40),
                        .winnow = "FALSE")

set.seed(300)
m_c50 <- train(default ~ ., data = credit, method = "C5.0",
                metric = "Kappa", trControl = ctrl,
               tuneGrid = grid_c50)
m_c50
#Test model


```